INSERT INTO airbnbdb.Category (PID, categoryName)
VALUES (1, 'Beachfront'),
       (1, 'Luxury'),
       (2, 'City Center'),
       (2, 'Modern'),
       (3, 'Mountain View'),
       (3, 'Cozy'),
       (4, 'Rural Retreat'),
       (4, 'Traditional'),
       (5, 'Ski-In/Ski-Out'),
       (5, 'Charming'),
       (6, 'Lakefront'),
       (6, 'Rustic'),
       (7, 'Villa'),
       (7, 'Contemporary'),
       (8, 'Urban Oasis'),
       (8, 'Industrial'),
       (9, 'Countryside'),
       (9, 'Quaint'),
       (10, 'Island Paradise'),
       (10, 'Tropical'),
       (11, 'Cabin'),
       (11, 'Secluded'),
       (12, 'Historic'),
       (12, 'Antique'),
       (13, 'Eco-Friendly'),
       (13, 'Green'),
       (14, 'Pet-Friendly'),
       (14, 'Casual'),
       (15, 'Unique'),
       (15, 'Eclectic');

