DROP TABLE IF EXISTS reviewforproperty;
CREATE TABLE ReviewForProperty(
GuestID INT,
PID INT ,
Created_Time Date NOT NULL,
Modified_Time Date,
CommentInReview VARCHAR(1000) ,
Cleanliness_Rating DECIMAL(2,1),
Communication_Rating DECIMAL(2,1),
CheckIn_Rating DECIMAL(2,1),
Accuracy_Rating DECIMAL(2,1),
Location_Rating DECIMAL(2,1),
Value_Rating DECIMAL(2,1),
Overall_Rating DECIMAL(2,1),
PRIMARY KEY(GuestID,PID));

DROP TABLE IF EXISTS PhotoForPropertyReview;
CREATE TABLE PhotoForPropertyReview(
GuestID INT ,
PID INT ,
PhotoName VARCHAR(50) ,
PRIMARY KEY(GuestID,PID,PhotoName));

DROP TABLE IF EXISTS PropertyIncludedInWishlist;
CREATE TABLE PropertyIncludedInWishlist(
PID INT ,
AirBnBUID INT ,
WishlistName VARCHAR(50) ,
CheckInDate DATE,
CheckOutDate DATE,
PRIMARY KEY(PID,AirBnBUID,WishlistName));

DROP TABLE IF EXISTS  WishList;
CREATE TABLE WishList(
AirBnBUID INT ,
WishlistName VARCHAR(50) NOT NULL UNIQUE,
Privacy CHAR(1),
PRIMARY KEY(AirBnBUID,WishlistName));

DROP TABLE IF EXISTS ReviewForUsers;
CREATE TABLE ReviewForUsers(
HostUID INT ,
GuestUID INT ,
GuestRating DECIMAL(2,1),HostRating DECIMAL(2,1),
CommentForHost VARCHAR(1000),
CommentForGuest VARCHAR(1000),
PRIMARY KEY(HostUID,GuestUID));

DROP TABLE IF EXISTS Message;
CREATE TABLE Message(
HostUID INT ,
GuestID INT ,
Created DATE NOT NULL,
Message_To INT NOT NULL,
Message_From INT NOT NULL,
Body VARCHAR(1000),
PRIMARY KEY(HostUID,GuestID));

DROP TABLE IF EXISTS Guest CASCADE ;
CREATE TABLE Guest(
AirBnBUID INT ,
AvgRating DECIMAL(2,1) ,
NumOfRatings INT DEFAULT 0,
PRIMARY KEY(AirBnBUID));

DROP TABLE IF EXISTS Host CASCADE ;
CREATE TABLE Host(
AirBnBUID INT ,
IsSuperHost CHAR(1) ,
AvgRating DECIMAL(2,1),
NumOfRatings INT,
PRIMARY KEY(AirBnBUID));

DROP TABLE IF EXISTS AirBnBUser;
CREATE TABLE AirBnBUser(
AirBnBUID INT,
DOB DATE,
Email VARCHAR(20) NOT NULL,
UserPassword VARCHAR(20) NOT NULL,
Gender CHAR(1),
About VARCHAR(100),
Phone VARCHAR(15) NOT NULL,
ProfilePhotoName VARCHAR(20),
Address VARCHAR(100),
Fname VARCHAR(20) NOT NULL,
LName VARCHAR(20),
PRIMARY KEY(AirBnBUID));

DROP TABLE IF EXISTS Amenity;
CREATE TABLE Amenity(
PID INT ,
AmenityName VARCHAR(20),
PRIMARY KEY(PID,AmenityName));



DROP TABLE IF EXISTS HouseRule;
CREATE TABLE HouseRule(
PID INT ,
RuleName VARCHAR(100),
PRIMARY KEY(PID,RuleName));

DROP TABLE IF EXISTS AvailableBookingSlot;
CREATE TABLE AvailableBookingSlot(
PID INT ,
StartDate DATE,
EndDate DATE,
PRIMARY KEY(PID,StartDate,EndDate));

DROP TABLE IF EXISTS Bedroom;
CREATE TABLE Bedroom(
PropertyID INT ,
BedroomNumber VARCHAR(5),
BedType VARCHAR(10),
BedCnt INT,
PRIMARY KEY(PropertyID,BedroomNumber,BedType,BedCnt));

DROP TABLE IF EXISTS Category;
CREATE TABLE Category(
PID INT ,
categoryName VARCHAR(20),
PRIMARY KEY(PID,categoryName));

DROP TABLE IF EXISTS PropertyListing CASCADE ;
CREATE TABLE PropertyListing(
PID INT ,
PropertyName VARCHAR(50) ,
Zipcode INT NOT NULL,
BathroomCnt INT,
BedroomCnt INT DEFAULT 0,
GuestNum INT,
PricePerNight DECIMAL(6,2),
CheckInTime TIMESTAMP(0),
CheckOutTime TIMESTAMP(0),
NumOfRatings INT DEFAULT 0,
AvgRatings DECIMAL(2,1) DEFAULT 0,
HID INT,
Street VARCHAR(20),
City VARCHAR(20),
Country VARCHAR(20),
PRIMARY KEY(PID));

DROP TABLE IF EXISTS Booking;
CREATE TABLE Booking(
BID INT,
CheckInDate DATE NOT NULL,
CheckOutDate DATE NOT NULL,
AmountPaid DECIMAL(6,2),
BookingDate DATE NOT NULL,
AdultGuestNum INT DEFAULT 0,
IsCancelled CHAR(1),
CancelDate DATE,
GuestUID INT,
PID INT,
TotalPrice DECIMAL(6,2),
TotalPriceWTax DECIMAL(6,2),
AmountDue DECIMAL(4,2),
PRIMARY KEY(BID));
ALTER TABLE Guest ADD CONSTRAINT GuestFK_1 FOREIGN KEY(AirBnBUID) REFERENCES
AirBnBUser(AirBnBUID) ON DELETE CASCADE;
ALTER TABLE Host ADD CONSTRAINT HostFK_1 FOREIGN KEY(AirBnBUID) REFERENCES
AirBnBUser(AirBnBUID) ON DELETE CASCADE ;

ALTER TABLE ReviewForProperty ADD CONSTRAINT ReviewForPropertyFK_1 FOREIGN
KEY(GuestID) REFERENCES Guest(AirBnBUID) ON DELETE CASCADE ;
ALTER TABLE ReviewForProperty ADD CONSTRAINT ReviewForPropertyFK_2 FOREIGN
KEY(PID) REFERENCES PropertyListing(PID) ON DELETE CASCADE ;
ALTER TABLE PhotoForPropertyReview ADD CONSTRAINT PhotoForPropertyReviewFK_1
FOREIGN KEY(GuestID) REFERENCES Guest(AirBnBUID) ON DELETE CASCADE ;
ALTER TABLE PhotoForPropertyReview ADD CONSTRAINT PhotoForPropertyReviewFK_2
FOREIGN KEY(PID) REFERENCES PropertyListing(PID) ON DELETE CASCADE ;
ALTER TABLE PropertyIncludedInWishlist ADD CONSTRAINT
PropertyIncludedInWishlistFK_1 FOREIGN KEY(AirBnBUID) REFERENCES
Guest(AirBnBUID) ON DELETE CASCADE ;ALTER TABLE PropertyIncludedInWishlist ADD CONSTRAINT
PropertyIncludedInWishlistFK_2 FOREIGN KEY(PID) REFERENCES
PropertyListing(PID) ON DELETE CASCADE ;
ALTER TABLE PropertyIncludedInWishlist ADD CONSTRAINT
PropertyIncludedInWishlistFK_3 FOREIGN KEY(WishlistName) REFERENCES
WishList(WishlistName) ON DELETE CASCADE;
ALTER TABLE WishList ADD CONSTRAINT WishListFK_1 FOREIGN KEY(AirBnBUID)
REFERENCES Guest(AirBnBUID) ON DELETE CASCADE;
ALTER TABLE ReviewForUsers ADD CONSTRAINT ReviewForUsersFK_1 FOREIGN
KEY(HostUID) REFERENCES Host(AirBnBUID) ON DELETE CASCADE ;
ALTER TABLE ReviewForUsers ADD CONSTRAINT ReviewForUsersFK_2 FOREIGN
KEY(GuestUID) REFERENCES Guest(AirBnBUID) ON DELETE CASCADE ;
ALTER TABLE Message ADD CONSTRAINT MessageFK_1 FOREIGN KEY(HostUID)
REFERENCES Host(AirBnBUID) ON DELETE CASCADE ;
ALTER TABLE Message ADD CONSTRAINT MessageFK_2 FOREIGN KEY(GuestID)
REFERENCES Guest(AirBnBUID) ON DELETE CASCADE ;
ALTER TABLE Amenity ADD CONSTRAINT AmenityFK_1 FOREIGN KEY(PID) REFERENCES
PropertyListing(PID) ON DELETE CASCADE ;
ALTER TABLE HouseRule ADD CONSTRAINT HouseRuleFK_1 FOREIGN KEY(PID)
REFERENCES PropertyListing(PID) ON DELETE CASCADE ;
ALTER TABLE AvailableBookingSlot ADD CONSTRAINT AvailableBookingSlotFK_1
FOREIGN KEY(PID) REFERENCES PropertyListing(PID) ON DELETE CASCADE ;
ALTER TABLE Bedroom ADD CONSTRAINT BedroomFK_1 FOREIGN KEY(PropertyID)
REFERENCES PropertyListing(PID) ON DELETE CASCADE ;
ALTER TABLE Category ADD CONSTRAINT CategoryFK_1 FOREIGN KEY(PID) REFERENCES
PropertyListing(PID) ON DELETE CASCADE ;
ALTER TABLE PROPERTYLISTING ADD CONSTRAINT propertyFK_1 FOREIGN KEY(HID)
REFERENCES Host(AIRBNBUID) ON DELETE CASCADE ;
ALTER TABLE Booking ADD CONSTRAINT BookingFK_1 FOREIGN KEY(GuestUID)
REFERENCES Guest(AirBnBUID) ON DELETE CASCADE ;
ALTER TABLE Booking ADD CONSTRAINT BookingFK_2 FOREIGN KEY(PID) REFERENCES
PropertyListing(PID) ON DELETE CASCADE ;
